package com.fitpal.app.data.repository

import com.fitpal.app.data.local.MealJson
import com.fitpal.app.data.local.dao.DailyMicros
import com.fitpal.app.data.local.dao.DailyNutritionRow
import com.fitpal.app.data.local.dao.DailyWaterRow
import com.fitpal.app.data.local.dao.DailyWaterSplit
import com.fitpal.app.data.local.dao.DistinctLoggedFood
import com.fitpal.app.data.local.dao.LoggedFoodRow
import com.fitpal.app.data.local.dao.MealLogDao
import com.fitpal.app.data.local.dao.MealLogItemWithType
import com.fitpal.app.data.local.entity.MealLogEntity
import com.fitpal.app.data.local.entity.MealLogItemEntity
import com.fitpal.app.domain.model.DetectedFood
import com.fitpal.app.domain.model.DietaryRuleKind
import com.fitpal.app.domain.model.Ingredient
import com.fitpal.app.domain.model.MealInsights
import com.fitpal.app.domain.model.Micronutrients
import com.fitpal.app.domain.model.MealTypes
import com.fitpal.app.domain.model.NutritionInfo
import com.fitpal.app.ml.AiSource
import com.fitpal.app.ml.DietaryClassifier
import com.fitpal.app.reminder.DietaryNotifier
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.combine
import java.time.LocalDate
import java.time.LocalTime
import java.time.format.DateTimeFormatter
import javax.inject.Inject
import javax.inject.Singleton

@Singleton
class MealRepository @Inject constructor(
    private val mealLogDao: MealLogDao,
    private val settingsRepository: SettingsRepository,
    private val insightsCacheDao: com.fitpal.app.data.local.dao.InsightsCacheDao,
    private val dietaryClassifier: DietaryClassifier,
    private val dietaryNotifier: DietaryNotifier,
    @dagger.hilt.android.qualifiers.ApplicationContext private val appContext: android.content.Context
) {
    private val dateFormat = DateTimeFormatter.ISO_LOCAL_DATE

    fun todayString(): String = LocalDate.now().format(dateFormat)

    // ---- Background AI overview (generated by InsightsWorker after each log) ----

    /** All items of a logged meal (one-shot), for the background overview generator. */
    suspend fun itemsForMeal(mealLogId: Long): List<MealLogItemEntity> = mealLogDao.getItemsForMeal(mealLogId)

    /** A cached AI overview for a food signature, or null if never generated. */
    suspend fun cachedInsights(signature: String): com.fitpal.app.data.local.entity.FoodInsightsCacheEntity? =
        insightsCacheDao.getBySignature(signature)

    /** Remember a food signature's AI overview so the same food reuses it instead of regenerating. */
    suspend fun cacheInsights(signature: String, insightsJson: String) =
        insightsCacheDao.upsert(
            com.fitpal.app.data.local.entity.FoodInsightsCacheEntity(signature, insightsJson, System.currentTimeMillis())
        )

    /** Enqueue the background overview generation for a just-logged meal (survives leaving the app). */
    private fun enqueueInsights(mealLogId: Long) {
        val request = androidx.work.OneTimeWorkRequestBuilder<com.fitpal.app.ml.InsightsWorker>()
            .setInputData(androidx.work.workDataOf(com.fitpal.app.ml.InsightsWorker.KEY_MEAL_LOG_ID to mealLogId))
            .build()
        androidx.work.WorkManager.getInstance(appContext)
            .enqueueUniqueWork("insights_$mealLogId", androidx.work.ExistingWorkPolicy.KEEP, request)
    }

    fun getMealsForDate(date: String): Flow<List<MealLogEntity>> =
        mealLogDao.getMealsForDate(date)

    fun getItemsForDate(date: String): Flow<List<MealLogItemEntity>> =
        mealLogDao.getAllItemsForDate(date)

    /** Today's items tagged with their meal category, for grouped display. */
    fun getItemsWithTypeForDate(date: String): Flow<List<MealLogItemWithType>> =
        mealLogDao.getItemsWithTypeForDate(date)

    /** The meal category for right now, per the user's configurable meal-time windows (#3). */
    fun defaultMealType(): String = settingsRepository.mealTypeForNow()

    /**
     * Get today's nutritional totals as a live-updating flow.
     */
    fun getDailyNutrition(date: String): Flow<NutritionInfo> = combine(
        mealLogDao.getTotalCaloriesForDate(date),
        mealLogDao.getTotalProteinForDate(date),
        mealLogDao.getTotalFatForDate(date),
        mealLogDao.getTotalCarbsForDate(date),
        mealLogDao.getTotalFiberForDate(date)
    ) { cal, pro, fat, carb, fib ->
        NutritionInfo(calories = cal, protein = pro, fat = fat, carbs = carb, fiber = fib)
    }

    /** Daily micronutrient totals (all seven in one query). */
    fun getDailyMicros(date: String): Flow<DailyMicros> =
        mealLogDao.getDailyMicrosForDate(date)

    /** Summed micronutrients across a date range — analytics deficiency breakdown. */
    fun getMicrosForRange(from: String, to: String): Flow<DailyMicros> =
        mealLogDao.getMicrosForRange(from, to)

    /** Per-day nutrition rows for a date range — drives analytics charts. */
    fun getDailyNutritionRange(from: String, to: String): Flow<List<DailyNutritionRow>> =
        mealLogDao.getDailyNutritionRange(from, to)

    /** Every logged food in a date range (name + calories + day) — so the AI review sees the meals. */
    suspend fun getLoggedFoodsInRange(from: String, to: String): List<LoggedFoodRow> =
        mealLogDao.getLoggedFoodsInRange(from, to)

    /** Protein summed per meal category over a range (+ days seen) — protein-distribution analysis. */
    suspend fun getProteinByMealTypeInRange(from: String, to: String): List<com.fitpal.app.data.local.dao.MealTypeProteinRow> =
        mealLogDao.getProteinByMealTypeInRange(from, to)

    /** Macros already eaten on [date] before [beforeTs] — "the day so far" for the meal coaching tip. */
    suspend fun macrosBefore(date: String, beforeTs: Long): com.fitpal.app.data.local.dao.MacroSums =
        mealLogDao.getMacrosBefore(date, beforeTs)

    /** Live item row — lets the detail screen show the AI overview the moment the background worker writes it. */
    fun observeItem(itemId: Long): Flow<MealLogItemEntity?> = mealLogDao.observeItemById(itemId)

    /** Each non-water meal's (day, log time) in a range — the fasting-adherence heatmap's raw data. */
    fun getMealTimesInRange(from: String, to: String): Flow<List<com.fitpal.app.data.local.dao.MealTimeRow>> =
        mealLogDao.getMealTimesInRange(from, to)

    /** Per-day water totals for a date range — analytics water chart. */
    fun getDailyWaterRange(from: String, to: String): Flow<List<DailyWaterRow>> =
        mealLogDao.getDailyWaterRange(from, to)

    /** Per-day water split into clear drinks vs. water from food. */
    fun getDailyWaterSplitRange(from: String, to: String): Flow<List<DailyWaterSplit>> =
        mealLogDao.getDailyWaterSplitRange(from, to)

    /** Days (newest first) the user logged real food — for the streak / Trail. */
    fun getLoggedDatesDesc(): Flow<List<String>> = mealLogDao.getLoggedDatesDesc()

    /** Recently logged distinct foods (newest first) — the Add screen's one-tap "Your usuals" row. */
    fun recentDistinctFoods(limit: Int = 12): Flow<List<MealLogItemEntity>> =
        mealLogDao.getRecentDistinctItems(limit)

    /** Every distinct food ever logged (real food only) — the global search's food source. */
    fun distinctLoggedFoods(): Flow<List<DistinctLoggedFood>> = mealLogDao.getDistinctLoggedFoods()

    /**
     * Re-log a previously logged item as a fresh one-food meal (one tap from "Your usuals"). Uses
     * the saved ingredient breakdown when present so it re-logs as the same composite dish, else
     * rebuilds a single ingredient from the item's totals.
     */
    suspend fun quickLogRecent(item: MealLogItemEntity, mealType: String, date: String? = null): Long {
        val ingredients = ingredientsForItem(item).ifEmpty { listOf(itemAsIngredient(item)) }
        val food = DetectedFood(
            label = item.name,
            confidence = 1f,
            boundingBox = android.graphics.RectF(),
            estimatedGrams = item.grams,
            ingredients = ingredients,
            isDrink = item.isDrink
        )
        return logMeal(listOf(food), mealType, date = date)
    }

    /** Rebuild a single per-100g ingredient from a logged item that has no saved breakdown. */
    private fun itemAsIngredient(item: MealLogItemEntity): Ingredient {
        val g = item.grams.takeIf { it > 0f } ?: 100f
        val f = 100f / g
        return Ingredient(
            name = item.name,
            grams = item.grams,
            caloriesPer100g = item.calories * f,
            proteinPer100g = item.protein * f,
            fatPer100g = item.fat * f,
            carbsPer100g = item.carbs * f,
            fiberPer100g = item.fiber * f,
            waterMlPer100g = item.waterMl * f,
            isDrink = item.isDrink,
            microsPer100g = Micronutrients(
                vitaminAMcg = item.vitaminA * f,
                vitaminCMg = item.vitaminC * f,
                vitaminDMcg = item.vitaminD * f,
                calciumMg = item.calcium * f,
                ironMg = item.iron * f,
                potassiumMg = item.potassium * f,
                sodiumMg = item.sodium * f,
                vitaminB12Mcg = item.vitaminB12 * f,
                folateMcg = item.folate * f,
                vitaminB6Mg = item.vitaminB6 * f,
                magnesiumMg = item.magnesium * f,
                zincMg = item.zinc * f,
                vitaminEMg = item.vitaminE * f
            )
        )
    }

    /**
     * Log a list of detected foods as a meal (e.g. everything on the plate).
     */
    suspend fun logMeal(
        foods: List<DetectedFood>,
        mealType: String,
        photoPath: String? = null,
        insights: MealInsights? = null,
        date: String? = null,
        source: AiSource? = null
    ): Long {
        val logDate = date ?: todayString()
        val mealLog = MealLogEntity(date = logDate, mealType = mealType)
        // Carry the meal's AI analysis onto each item so opening it later shows the
        // saved review instead of regenerating.
        val insightsJson = insights?.let { MealJson.encodeInsights(it) }
        val insightsAt = if (insights != null) System.currentTimeMillis() else 0L
        // Tag each item with the dietary-rule categories it counts toward (dessert / fried / drink).
        val ruleTags = tagsFor(foods.map { it.label })
        val items = foods.mapIndexed { index, food ->
            val micros = food.totalMicros
            MealLogItemEntity(
                mealLogId = 0, // set by DAO
                name = food.label,
                grams = food.totalGrams,
                calories = food.totalCalories,
                protein = food.totalProtein,
                fat = food.totalFat,
                carbs = food.totalCarbs,
                fiber = food.totalFiber,
                isDrink = food.isDrink,
                // Count water from every source — drinks AND watery foods (fruit, soup…).
                waterMl = food.totalWaterMl,
                vitaminA = micros.vitaminAMcg,
                vitaminC = micros.vitaminCMg,
                vitaminD = micros.vitaminDMcg,
                calcium = micros.calciumMg,
                iron = micros.ironMg,
                potassium = micros.potassiumMg,
                sodium = micros.sodiumMg,
                vitaminB12 = micros.vitaminB12Mcg,
                folate = micros.folateMcg,
                vitaminB6 = micros.vitaminB6Mg,
                magnesium = micros.magnesiumMg,
                zinc = micros.zincMg,
                vitaminE = micros.vitaminEMg,
                photoPath = photoPath,
                // Keep the ingredient breakdown so the detail screen can show/edit it.
                ingredientsJson = MealJson.encodeIngredients(food.ingredients),
                insightsJson = insightsJson,
                insightsGeneratedAt = insightsAt,
                aiSource = source?.storedName,
                aiModel = source?.model,
                ruleTags = DietaryRuleKind.tagsToDb(ruleTags.getOrElse(index) { emptySet() })
            )
        }
        val mealLogId = mealLogDao.logMealWithItems(mealLog, items)
        enqueueInsights(mealLogId)
        maybeNotifyDietary(logDate)
        return mealLogId
    }

    /**
     * Log a list of individual food items as one meal.
     * Used by Manual Entry and Describe-to-AI, where each item is a single ingredient.
     */
    suspend fun logItems(
        items: List<Ingredient>,
        mealType: String,
        date: String? = null
    ): Long {
        val logDate = date ?: todayString()
        val mealLog = MealLogEntity(date = logDate, mealType = mealType)
        val ruleTags = tagsFor(items.map { it.name })
        val logItems = items.mapIndexed { index, ingredient ->
            val m = ingredient.micros
            MealLogItemEntity(
                mealLogId = 0, // set by DAO
                name = ingredient.name,
                grams = ingredient.grams,
                calories = ingredient.calories,
                protein = ingredient.protein,
                fat = ingredient.fat,
                carbs = ingredient.carbs,
                fiber = ingredient.fiber,
                isDrink = ingredient.isDrink,
                waterMl = ingredient.waterMl,
                vitaminA = m.vitaminAMcg,
                vitaminC = m.vitaminCMg,
                vitaminD = m.vitaminDMcg,
                calcium = m.calciumMg,
                iron = m.ironMg,
                potassium = m.potassiumMg,
                sodium = m.sodiumMg,
                vitaminB12 = m.vitaminB12Mcg,
                folate = m.folateMcg,
                vitaminB6 = m.vitaminB6Mg,
                magnesium = m.magnesiumMg,
                zinc = m.zincMg,
                vitaminE = m.vitaminEMg,
                // Store the item itself as its single ingredient so the detail editor works.
                ingredientsJson = MealJson.encodeIngredients(listOf(ingredient)),
                ruleTags = DietaryRuleKind.tagsToDb(ruleTags.getOrElse(index) { emptySet() })
            )
        }
        val mealLogId = mealLogDao.logMealWithItems(mealLog, logItems)
        enqueueInsights(mealLogId)
        maybeNotifyDietary(logDate)
        return mealLogId
    }

    // ---- Dietary rules: tagging, live totals, and the over-limit notification ----

    /** Classify [names] into their enabled dietary-rule categories (empty when no rules are on). */
    private suspend fun tagsFor(names: List<String>): List<Set<DietaryRuleKind>> {
        val enabled = settingsRepository.dietaryRules.value.filter { it.enabled }.map { it.kind }.toSet()
        if (enabled.isEmpty() || names.isEmpty()) return names.map { emptySet() }
        return runCatching { dietaryClassifier.tagFoods(names, enabled) }
            .getOrElse { names.map { emptySet() } }
    }

    /** After a log lands on today, notify (once/day) for any enabled rule whose cap was just passed. */
    private suspend fun maybeNotifyDietary(logDate: String) {
        if (logDate != todayString()) return
        val rules = settingsRepository.dietaryRules.value.filter { it.enabled && it.notify }
        if (rules.isEmpty()) return
        val items = mealLogDao.getItemsForDateOnce(logDate)
        rules.forEach { rule ->
            val consumed = items
                .filter { DietaryRuleKind.tagsFromDb(it.ruleTags).contains(rule.kind) }
                .sumOf { it.calories.toDouble() }.toInt()
            if (rule.dailyLimitKcal in 1..consumed && !settingsRepository.isDietaryNotifiedToday(rule.kind)) {
                dietaryNotifier.notifyLimitReached(rule.kind, consumed, rule.dailyLimitKcal)
                settingsRepository.markDietaryNotified(rule.kind)
            }
        }
    }

    /** Live total calories on [date] counting toward one dietary rule — drives the Home strip. */
    fun dietaryConsumedForDate(date: String, kind: DietaryRuleKind): Flow<Float> =
        mealLogDao.getTaggedCaloriesForDate(date, kind.likePattern)

    /** One-shot per-rule consumed totals for [date] — used by the pre-log gate. */
    suspend fun dietaryConsumedTodayOnce(date: String): Map<DietaryRuleKind, Int> {
        val items = mealLogDao.getItemsForDateOnce(date)
        return DietaryRuleKind.entries.associateWith { kind ->
            items.filter { DietaryRuleKind.tagsFromDb(it.ruleTags).contains(kind) }
                .sumOf { it.calories.toDouble() }.toInt()
        }
    }

    /** Log plain water (a quick-add). Counts fully toward water intake, never shown among meals. */
    suspend fun logWater(ml: Float, date: String? = null): Long {
        val logDate = date ?: todayString()
        // Tag with the "water" sentinel category so it stays out of Breakfast/Lunch/… on Home.
        val mealLog = MealLogEntity(date = logDate, mealType = MealTypes.WATER)
        val item = MealLogItemEntity(
            mealLogId = 0,
            name = "Water",
            grams = ml,
            calories = 0f,
            protein = 0f,
            fat = 0f,
            carbs = 0f,
            fiber = 0f,
            isDrink = true,
            waterMl = ml
        )
        return mealLogDao.logMealWithItems(mealLog, listOf(item))
    }

    fun getTotalWaterForDate(date: String): Flow<Float> =
        mealLogDao.getTotalWaterForDate(date)

    suspend fun getItemById(itemId: Long): MealLogItemEntity? = mealLogDao.getItemById(itemId)

    suspend fun getMealTypeForItem(itemId: Long): String? = mealLogDao.getMealTypeForItem(itemId)

    suspend fun deleteMeal(id: Long) = mealLogDao.deleteMealLog(id)

    suspend fun deleteItem(id: Long) = mealLogDao.deleteItem(id)

    /**
     * Duplicate a single logged item onto another day, keeping its meal category. Used by the
     * "copy to another date" action. The copy gets fresh ids (id/mealLogId reset to 0).
     */
    suspend fun copyItemToDate(item: MealLogItemEntity, date: String, mealType: String? = null) {
        val type = mealType ?: mealLogDao.getMealTypeForItem(item.id) ?: defaultMealType()
        // Carry the coach's note from the item's meal onto the copy — copying is to a nearby day, so a
        // day-relative note stays sensible, and losing it on every copy was the complaint. (Copies go
        // straight to the DAO without enqueueing InsightsWorker, so nothing regenerates over it.)
        val coachingTipJson = mealLogDao.getMealLogById(item.mealLogId)?.coachingTipJson
        val mealLog = MealLogEntity(date = date, mealType = type, coachingTipJson = coachingTipJson)
        mealLogDao.logMealWithItems(mealLog, listOf(item.copy(id = 0, mealLogId = 0)))
    }

    // ---- Change meal category (Breakfast/Lunch/Dinner/Snack) after logging ----

    /** Change a whole logged meal's category (all its dishes move together). */
    suspend fun setMealMealType(mealLogId: Long, newMealType: String) =
        mealLogDao.updateMealLogType(mealLogId, newMealType)

    /**
     * Change a single logged item's category. If it's the only item in its meal log, just retag
     * the log; otherwise move the item to its own new meal log of the new category (same day),
     * keeping the item's id stable so any open detail screen stays valid.
     */
    suspend fun setItemMealType(item: MealLogItemEntity, newMealType: String) {
        val siblings = mealLogDao.getItemsForMeal(item.mealLogId)
        if (siblings.size <= 1) {
            mealLogDao.updateMealLogType(item.mealLogId, newMealType)
        } else {
            val date = mealLogDao.getMealDate(item.mealLogId) ?: todayString()
            val newLogId = mealLogDao.insertMealLog(MealLogEntity(date = date, mealType = newMealType))
            mealLogDao.updateItemMealLog(item.id, newLogId)
        }
    }

    // ---- Whole meal group (one generation = one photo/describe), for the multi-dish meal screen ----

    /** Live items of one meal log. */
    fun getItemsForMealFlow(mealLogId: Long): Flow<List<MealLogItemEntity>> =
        mealLogDao.getItemsForMealFlow(mealLogId)

    /** The meal category of a whole meal log. */
    suspend fun getMealTypeForMeal(mealLogId: Long): String? =
        mealLogDao.getMealTypeForMeal(mealLogId)

    /** The calendar day (ISO) a meal log belongs to. */
    suspend fun getMealDate(mealLogId: Long): String? =
        mealLogDao.getMealDate(mealLogId)

    /** Duplicate a whole meal (all its dishes) onto another day. Keeps its category unless one is given. */
    suspend fun copyMealToDate(mealLogId: Long, date: String, mealType: String? = null) {
        val items = mealLogDao.getItemsForMeal(mealLogId)
        if (items.isEmpty()) return
        val type = mealType ?: mealLogDao.getMealTypeForMeal(mealLogId) ?: defaultMealType()
        // Carry the meal's name + situation tag too — a copy of "Sunday roast" is still Sunday roast.
        val original = mealLogDao.getMealLogById(mealLogId)
        val mealLog = MealLogEntity(
            date = date,
            mealType = type,
            name = mealLogDao.getMealName(mealLogId),
            context = original?.context,
            // Carry the coach's note too — a copy of the meal keeps its note (it's judged against the
            // day, and a copy lands on a nearby day, so it stays relevant). Copies bypass
            // InsightsWorker, so nothing overwrites it.
            coachingTipJson = original?.coachingTipJson
        )
        mealLogDao.logMealWithItems(mealLog, items.map { it.copy(id = 0, mealLogId = 0) })
    }

    // ---- Meal situation tag ("Home"/"Restaurant"/…) + cached meal-level coaching tip ----

    /** Live meal row — the group screen watches it for the coaching tip the worker writes. */
    fun observeMealLog(mealLogId: Long): Flow<MealLogEntity?> =
        mealLogDao.observeMealLogById(mealLogId)

    /** One-shot meal row, for reading its context / coaching tip. */
    suspend fun getMealLog(mealLogId: Long): MealLogEntity? = mealLogDao.getMealLogById(mealLogId)

    /** Set (or clear, with null) the one-tap situation tag on a whole meal. */
    suspend fun updateMealContext(mealLogId: Long, context: String?) =
        mealLogDao.updateMealContext(mealLogId, context?.takeIf { it.isNotBlank() })

    /** Save (or clear) the cached meal-level coaching tip. */
    suspend fun saveCoachingTip(mealLogId: Long, tip: com.fitpal.app.domain.model.CoachingTip?) =
        mealLogDao.updateCoachingTip(mealLogId, tip?.let { MealJson.encodeCoachingTip(it) })

    /** Decode a meal's cached coaching tip, or null if none / unparseable. */
    fun coachingTipFor(meal: MealLogEntity): com.fitpal.app.domain.model.CoachingTip? =
        MealJson.decodeCoachingTip(meal.coachingTipJson)

    // ---- Ingredient breakdown + cached AI insights (meal detail screen) ----

    /** The ingredients that make up a logged item (empty if none were saved). */
    fun ingredientsForItem(item: MealLogItemEntity): List<Ingredient> =
        MealJson.decodeIngredients(item.ingredientsJson)

    /** Cached AI insights for an item, or null if none / wiped by retention. */
    fun insightsForItem(item: MealLogItemEntity): MealInsights? =
        MealJson.decodeInsights(item.insightsJson)

    /** Save freshly generated insights so we don't regenerate next time. */
    suspend fun saveInsights(itemId: Long, insights: MealInsights) {
        mealLogDao.updateInsights(itemId, MealJson.encodeInsights(insights), System.currentTimeMillis())
    }

    /** Forget cached insights (used by the 1-month retention sweep). */
    suspend fun clearInsights(itemId: Long) {
        mealLogDao.updateInsights(itemId, null, 0L)
    }

    /**
     * Rename a logged item — by hand from the meal screens, or when an AI edit re-identifies the
     * dish. Works for anything logged, including foods that came from the database under a long
     * catalogue name. Blank names are ignored (a nameless entry helps nobody).
     */
    suspend fun renameItem(itemId: Long, name: String) {
        val clean = name.trim()
        if (clean.isNotEmpty()) mealLogDao.updateItemName(itemId, clean)
    }

    /**
     * Name a whole meal — the dishes logged together in one go ("Sunday roast"). A blank name
     * clears it, so the meal goes back to being described by its dishes.
     */
    suspend fun renameMeal(mealLogId: Long, name: String?) {
        mealLogDao.updateMealLogName(mealLogId, name?.trim()?.takeIf { it.isNotEmpty() })
    }

    /** The name the user gave a meal, or null if it's unnamed. */
    suspend fun getMealName(mealLogId: Long): String? = mealLogDao.getMealName(mealLogId)

    /**
     * Replace an item's ingredient list and recompute every total from it.
     * Drives the add/remove/edit-grams controls on the meal detail screen.
     */
    suspend fun updateItemIngredients(itemId: Long, ingredients: List<Ingredient>) {
        val micros = ingredients.fold(Micronutrients()) { acc, ing -> acc + ing.micros }
        mealLogDao.updateItemWithIngredients(
            id = itemId,
            ingredientsJson = MealJson.encodeIngredients(ingredients),
            grams = ingredients.sumOf { it.grams.toDouble() }.toFloat(),
            calories = ingredients.sumOf { it.calories.toDouble() }.toFloat(),
            protein = ingredients.sumOf { it.protein.toDouble() }.toFloat(),
            fat = ingredients.sumOf { it.fat.toDouble() }.toFloat(),
            carbs = ingredients.sumOf { it.carbs.toDouble() }.toFloat(),
            fiber = ingredients.sumOf { it.fiber.toDouble() }.toFloat(),
            waterMl = ingredients.sumOf { it.waterMl.toDouble() }.toFloat(),
            vitaminA = micros.vitaminAMcg,
            vitaminC = micros.vitaminCMg,
            vitaminD = micros.vitaminDMcg,
            calcium = micros.calciumMg,
            iron = micros.ironMg,
            potassium = micros.potassiumMg,
            sodium = micros.sodiumMg,
            vitaminB12 = micros.vitaminB12Mcg,
            folate = micros.folateMcg,
            vitaminB6 = micros.vitaminB6Mg,
            magnesium = micros.magnesiumMg,
            zinc = micros.zincMg,
            vitaminE = micros.vitaminEMg
        )
    }

    /**
     * Change a logged item's weight, scaling its calories and macros proportionally.
     *
     * If the item has a saved ingredient breakdown, scale that too and re-persist through the same
     * path the detail editor uses — otherwise `ingredientsJson` would keep the OLD weight, and the
     * detail screen (which reads the breakdown) would silently revert this edit the next time it's
     * touched. For older entries with no breakdown we scale the stored totals directly.
     */
    suspend fun updateItemGrams(item: MealLogItemEntity, newGrams: Float) {
        if (newGrams <= 0f || item.grams <= 0f) return
        val breakdown = ingredientsForItem(item)
        val breakdownGrams = breakdown.sumOf { it.grams.toDouble() }.toFloat()
        if (breakdown.isNotEmpty() && breakdownGrams > 0f) {
            // Scale the breakdown so it sums to the new total (relative to the breakdown's own
            // weight, which also heals any row left inconsistent by the old code path), then
            // re-persist through the detail editor's path so ingredientsJson stays consistent.
            val f = newGrams / breakdownGrams
            updateItemIngredients(item.id, breakdown.map { it.withGrams(it.grams * f) })
            return
        }
        val factor = newGrams / item.grams
        mealLogDao.updateItem(
            id = item.id,
            grams = newGrams,
            calories = item.calories * factor,
            protein = item.protein * factor,
            fat = item.fat * factor,
            carbs = item.carbs * factor,
            fiber = item.fiber * factor,
            waterMl = item.waterMl * factor,
            vitaminA = item.vitaminA * factor,
            vitaminC = item.vitaminC * factor,
            vitaminD = item.vitaminD * factor,
            calcium = item.calcium * factor,
            iron = item.iron * factor,
            potassium = item.potassium * factor,
            sodium = item.sodium * factor,
            vitaminB12 = item.vitaminB12 * factor,
            folate = item.folate * factor,
            vitaminB6 = item.vitaminB6 * factor,
            magnesium = item.magnesium * factor,
            zinc = item.zinc * factor,
            vitaminE = item.vitaminE * factor
        )
    }
}
